/**
 * @file rl_control_state_remote.hpp
 * @brief RL control state that receives joint commands from a remote Jetson NX
 * @author Generated by Claude Code
 * @version 1.0
 * @date 2025-06-12
 *
 * Replaces local ONNX inference with network communication:
 *   - Sends sensor data + gamepad input to NX via CommBridge (~50 Hz)
 *   - Receives joint position commands from NX and passes them to the robot
 *     interface at 2 kHz (zero-order hold between NX updates).
 *   - PD tracking is handled by the robot's motor controller (real hardware)
 *     or by the simulator (PyBullet/MuJoCo).
 *
 * Safety fallbacks (in LoseControlJudge):
 *   1. User requests JointDamping via gamepad
 *   2. Posture violation (roll > 30°, pitch > 45°) — same as ONNX state
 *   3. Communication timeout (no command from NX for > timeout_ms)
 */

#pragma once

#include "state_base.h"
#include "comm_bridge.hpp"

#include <cmath>
#include <cstring>

// ============================================================================
// Deployment-specific configuration — edit these for your setup
// ============================================================================

/// IP address of the Jetson NX on the direct link to RK3588.
/// Use "127.0.0.1" for same-machine simulation testing.
#ifndef NX_IP_ADDRESS
#define NX_IP_ADDRESS "127.0.0.1"
#endif

/// Default safe PD gains used before the first NX command arrives,
/// and as fallback if NX sends zeros.
constexpr float DEFAULT_KP = 30.0f;
constexpr float DEFAULT_KD = 1.0f;

// ============================================================================
// RLControlStateRemote
// ============================================================================

class RLControlStateRemote : public StateBase
{
private:
    RobotBasicState rbs_;
    int state_run_cnt_;

    std::shared_ptr<CommBridge> comm_;

    /// The last joint command sent to the robot — held between NX updates (ZOH).
    /// Pre-allocated and reused to avoid heap allocation in the 2 kHz hot path.
    MatXf last_joint_command_;

    /// Whether we have ever received a command from NX in this session.
    bool has_received_command_;

    /// Cached user command for the current tick — avoids calling GetUserCommand()
    /// multiple times (UpdateRobotObservation, Run, LoseControlJudge).
    UserCommand cached_uc_;

    /// Read all sensor data from the robot interface into rbs_.
    /// Optimised for the remote state: only reads values that are actually used.
    /// - rpy/acc/omega/joint_* — sent to NX via CommBridge
    /// - cmd_vel — forwarded to NX as user command velocity
    /// NOTE: base_rot_mat and projected_gravity are NOT computed here;
    ///       they were only needed by local ONNX inference. The NX side
    ///       computes projected_gravity from rpy via NxRobotState::projected_gravity.
    void UpdateRobotObservation()
    {
        rbs_.base_rpy = ri_ptr_->GetImuRpy();
        rbs_.base_omega = ri_ptr_->GetImuOmega();
        rbs_.base_acc = ri_ptr_->GetImuAcc();
        rbs_.joint_pos = ri_ptr_->GetJointPosition();
        rbs_.joint_vel = ri_ptr_->GetJointVelocity();
        rbs_.joint_tau = ri_ptr_->GetJointTorque();

        cached_uc_ = uc_ptr_->GetUserCommand();
        rbs_.cmd_vel_normlized = Vec3f(
            cached_uc_.forward_vel_scale,
            cached_uc_.side_vel_scale,
            cached_uc_.turnning_vel_scale);
    }

    /// Apply the latest NX command (or safe hold) to the robot.
    /// Uses the pre-allocated last_joint_command_ to avoid heap allocation.
    void ApplyJointCommand()
    {
        bool got_cmd = comm_->GetLatestCommand(last_joint_command_);

        if (got_cmd)
        {
            // Use NX-provided command; fill in safe defaults for zero gains
            for (int i = 0; i < 12; ++i)
            {
                if (last_joint_command_(i, 0) <= 0.0f)
                    last_joint_command_(i, 0) = DEFAULT_KP;
                if (last_joint_command_(i, 2) <= 0.0f)
                    last_joint_command_(i, 2) = DEFAULT_KD;
            }
            has_received_command_ = true;
        }
        else if (!has_received_command_)
        {
            // No command ever received yet — hold current joint positions
            VecXf current_pos = ri_ptr_->GetJointPosition();
            for (int i = 0; i < 12; ++i)
            {
                last_joint_command_(i, 0) = DEFAULT_KP;
                last_joint_command_(i, 1) = current_pos(i);
                last_joint_command_(i, 2) = DEFAULT_KD;
                last_joint_command_(i, 3) = 0.0f;
                last_joint_command_(i, 4) = 0.0f;
            }
        }
        // else: no new command but has_received_command_ is true
        //       → continue using last_joint_command_ (ZOH)

        ri_ptr_->SetJointCommand(last_joint_command_);
    }

public:
    RLControlStateRemote(const RobotType &robot_type,
                         const std::string &state_name,
                         std::shared_ptr<ControllerData> data_ptr)
        : StateBase(robot_type, state_name, data_ptr)
    {
        std::memset(&rbs_, 0, sizeof(rbs_));
        last_joint_command_ = MatXf::Zero(12, 5);
        has_received_command_ = false;
        std::memset(&cached_uc_, 0, sizeof(cached_uc_));

        comm_ = std::make_shared<CommBridge>(NX_IP_ADDRESS);
        std::cout << "[RLControlStateRemote] NX target: " << NX_IP_ADDRESS
                  << ", send port: " << DEFAULT_SENSOR_PORT
                  << ", recv port: " << DEFAULT_COMMAND_PORT << std::endl;
    }

    ~RLControlStateRemote() {}

    // ========================================================================
    // StateBase interface
    // ========================================================================

    virtual void OnEnter() override
    {
        state_run_cnt_ = -1;
        has_received_command_ = false;
        last_joint_command_ = MatXf::Zero(12, 5);

        // Initialize the hold position to the current joint positions
        // so we don't command a jump on first tick.
        VecXf init_pos = ri_ptr_->GetJointPosition();
        for (int i = 0; i < 12; ++i)
        {
            last_joint_command_(i, 0) = DEFAULT_KP;
            last_joint_command_(i, 1) = init_pos(i);
            last_joint_command_(i, 2) = DEFAULT_KD;
        }

        comm_->Start();

        StateBase::msfb_.UpdateCurrentState(RobotMotionState::RLControlMode);
        uc_ptr_->SetMotionStateFeedback(StateBase::msfb_);

        std::cout << "[RLControlStateRemote] Entered — waiting for NX commands" << std::endl;
    }

    virtual void OnExit() override
    {
        comm_->Stop();
        state_run_cnt_ = -1;
        has_received_command_ = false;
        std::cout << "[RLControlStateRemote] Exited" << std::endl;
    }

    virtual void Run() override
    {
        UpdateRobotObservation();  // also caches UserCommand in cached_uc_

        // Update the sensor data that CommBridge will send to NX.
        // Uses the cached UserCommand to avoid a second GetUserCommand() call.
        uint32_t ts_ms = static_cast<uint32_t>(ri_ptr_->GetInterfaceTimeStamp() * 1000.0);
        comm_->UpdateSensorData(rbs_, cached_uc_,
                                RobotMotionState::RLControlMode, ts_ms);

        // Apply the latest joint command from NX (or ZOH) to the robot
        ApplyJointCommand();

        state_run_cnt_++;
    }

    virtual bool LoseControlJudge() override
    {
        // 1. User requested JointDamping via gamepad (uses cached value from Run())
        if (cached_uc_.target_mode == int(RobotMotionState::JointDamping))
        {
            std::cout << "[RLControlStateRemote] User requested JointDamping" << std::endl;
            return true;
        }

        // 2. Posture safety check (roll > 30° or pitch > 45°)
        if (PostureUnsafeCheck())
        {
            return true;
        }

        // 3. Communication timeout — no command from NX
        if (comm_->IsTimeout())
        {
            std::cout << "[RLControlStateRemote] Communication timeout — "
                      << comm_->GetMissedPackets() << " missed packets"
                      << std::endl;
            return true;
        }

        return false;
    }

    virtual StateName GetNextStateName() override
    {
        return StateName::kRLControl;
    }

private:
    /// Check if the robot's posture exceeds safe limits.
    /// Same thresholds as the ONNX version: roll ±30°, pitch ±45°.
    bool PostureUnsafeCheck()
    {
        Vec3f rpy = ri_ptr_->GetImuRpy();
        if (std::fabs(rpy(0)) > 30.0 / 180.0 * M_PI ||
            std::fabs(rpy(1)) > 45.0 / 180.0 * M_PI)
        {
            std::cout << "[RLControlStateRemote] Posture unsafe — rpy: "
                      << (180.0 / M_PI * rpy.transpose()) << std::endl;
            return true;
        }
        return false;
    }
};
