/**
 * @file nx_bridge_api.hpp
 * @brief Public API for the Jetson NX side of the RK3588–NX communication bridge
 * @author Generated by Claude Code
 * @version 1.0
 * @date 2025-06-12
 *
 * ## Quick Start
 *
 * ```cpp
 * #include "nx_bridge_api.hpp"
 *
 * NxJointCommand my_policy(const NxRobotState& state) {
 *     NxJointCommand cmd;
 *     // Fill cmd.joint_pos_des[0..11] with your policy output...
 *     // Default gains: kp=30, kd=1, tau_ff=0, vel_des=0
 *     for (int i = 0; i < 12; i++) {
 *         cmd.kp[i] = 30.0f;
 *         cmd.kd[i] = 1.0f;
 *     }
 *     return cmd;
 * }
 *
 * int main() {
 *     NxBridge bridge(31001, "192.168.1.100", 31002);
 *     bridge.Start(my_policy, 20.0f);  // 50 Hz
 *     // ... your program runs; bridge handles networking in background ...
 *     bridge.Stop();
 * }
 * ```
 *
 * ## Design
 *
 * The NxBridge starts two internal threads:
 *   - Recv thread: receives SensorPacket from RK3588, calls the observation
 *     callback with deserialised data.
 *   - Send thread: periodically calls the action callback and sends the
 *     resulting CommandPacket to RK3588.
 *
 * The developer does not need to manage sockets, threads, or serialisation.
 */

#pragma once

#include <cstdint>
#include <cmath>
#include <functional>
#include <memory>
#include <string>

// ============================================================================
// Data structures  (same layout as the RK3588 side)
// ============================================================================

/// Sensor + gamepad data received from the robot (via RK3588)
struct NxRobotState {
    uint32_t seq;               ///< Monotonic sequence number
    uint32_t timestamp_ms;      ///< Millisecond timestamp
    int32_t  current_state;     ///< RobotMotionState enum value
    float    rpy[3];            ///< Roll, pitch, yaw [rad]
    float    acc[3];            ///< Base acceleration [m/s²]
    float    omega[3];          ///< Body-frame angular velocity [rad/s]
    float    joint_pos[12];     ///< Joint positions [rad]
    float    joint_vel[12];     ///< Joint velocities [rad/s]
    float    joint_tau[12];     ///< Joint torques [Nm]
    float    cmd_vel[3];        ///< User command velocity (normalised)

    /**
     * @brief Compute the gravity vector projected into the body frame.
     *
     * Uses ZYX Euler convention (matching the robot-side RpyToRm):
     *   projected_gravity = R_body_to_world^T * (0, 0, -1)
     *
     * Result:
     *   x =  sin(pitch)
     *   y = -cos(pitch) * sin(roll)
     *   z = -cos(pitch) * cos(roll)
     *
     * This is the same computation done on the RK3588 for ONNX policy input,
     * provided here for convenience so NX-side policies can use it directly.
     */
    void getProjectedGravity(float g[3]) const {
        float cp = std::cos(rpy[1]);  // cos(pitch)
        g[0] = std::sin(rpy[1]);       //  sin(pitch)
        g[1] = -cp * std::sin(rpy[0]); // -cos(pitch) * sin(roll)
        g[2] = -cp * std::cos(rpy[0]); // -cos(pitch) * cos(roll)
    }
};

/// Joint command to send back to the robot (via RK3588)
struct NxJointCommand {
    float joint_pos_des[12];    ///< Desired joint positions [rad]
    float joint_vel_des[12];    ///< Desired joint velocities [rad/s] (usually 0)
    float kp[12];               ///< PD proportional gains (default 30)
    float kd[12];               ///< PD derivative gains (default 1)
    float tau_ff[12];           ///< Feed-forward torque [Nm] (default 0)
};

// ============================================================================
// Callback types
// ============================================================================

/**
 * @brief Observation callback — called when new sensor data arrives from RK3588.
 *
 * This runs in the internal receive thread. Keep it fast; if heavy processing
 * is needed, copy the data and process it in another thread.
 *
 * @param state  Latest sensor + gamepad data from the robot
 */
using ObservationCallback = std::function<void(const NxRobotState& state)>;

/**
 * @brief Action callback — called periodically to get the next joint command.
 *
 * This runs in the internal send thread at the configured rate (default 50 Hz).
 * The returned command is sent to RK3588, which applies PD tracking at 2 kHz.
 *
 * @return The joint command to send. If the same command is returned every
 *         call, RK3588 applies a zero-order hold — the robot holds position.
 */
using ActionCallback = std::function<NxJointCommand()>;

// ============================================================================
// NxBridge
// ============================================================================

class NxBridge {
public:
    /**
     * @brief Construct the bridge.
     * @param recv_port  Local port to bind for receiving SensorPackets (e.g. 31001)
     * @param robot_ip   IP address of the RK3588
     * @param send_port  Port on RK3588 to send CommandPackets to (e.g. 31002)
     */
    NxBridge(int recv_port, const std::string& robot_ip, int send_port);

    ~NxBridge();

    // --- Lifecycle ---

    /**
     * @brief Start the bridge.
     *
     * Launches two internal threads:
     *   - Recv: blocks on SensorPacket, calls on_obs on each received packet.
     *   - Send: calls get_act at the configured rate, sends the result.
     *
     * @param on_obs     Called when a SensorPacket arrives (in recv thread).
     * @param get_act    Called periodically to obtain the next command (in send thread).
     * @param period_ms  Send interval in milliseconds (default 20 → 50 Hz).
     */
    void Start(ObservationCallback on_obs, ActionCallback get_act,
               float period_ms = 20.0f);

    /**
     * @brief Overload: observation-only callback (no separate action callback).
     *
     * The action callback is the same as the observation callback — called
     * at the send rate. Useful when the policy runs synchronously with sensor
     * updates, or when the callback maintains internal state.
     */
    void Start(std::function<NxJointCommand(const NxRobotState&)> policy,
               float period_ms = 20.0f);

    /// Stop all threads and close sockets.
    void Stop();

    // --- Helpers ---

    /// Send an explicit shutdown signal to RK3588, triggering JointDamping.
    void SendShutdown();

    /// Configure the default PD gains used when the returned command has zeros.
    static void SetDefaultGains(float kp, float kd);

private:
    // Implementation hidden in .cpp (PIMPL pattern to keep this header clean)
    struct Impl;
    std::unique_ptr<Impl> impl_;
};
