/**
 * @file comm_bridge.hpp
 * @brief RK3588-side UDP communication bridge to Jetson NX
 * @author Generated by Claude Code
 * @version 1.0
 * @date 2025-06-12
 *
 * Manages two UDP sockets:
 *   - Send socket:   streams SensorPacket to NX at configurable rate (~50 Hz)
 *   - Recv socket:   blocks on CommandPacket from NX, stores atomically for main loop
 *
 * Thread safety:
 *   - GetLatestCommand() uses a std::mutex to safely copy the latest CommandPacket.
 *   - UpdateSensorData() uses a separate std::mutex for the pending send buffer.
 *   - Both are designed to never block the 2 kHz main control loop.
 *
 * Timeout handling:
 *   - If no CommandPacket arrives within timeout_ms_ (default 40 ms),
 *     IsTimeout() returns true, triggering LoseControlJudge → JointDamping.
 */

#pragma once

#include "nx_network_codes.hpp"

#include <iostream>
#include <cstring>
#include <string>
#include <thread>
#include <mutex>
#include <atomic>
#include <chrono>

#include <sys/types.h>
#include <sys/socket.h>
#include <sys/timerfd.h>
#include <sys/epoll.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>

#include "common_types.h"
#include "custom_types.h"
using namespace types;

class CommBridge {
public:
    // ========================================================================
    // Construction / Destruction
    // ========================================================================

    /**
     * @param nx_ip       IP address of the Jetson NX (e.g. "192.168.1.103")
     * @param send_port   Port on NX that receives SensorPackets (default 31001)
     * @param recv_port   Local port to bind for receiving CommandPackets (default 31002)
     */
    CommBridge(const std::string& nx_ip,
               int send_port = DEFAULT_SENSOR_PORT,
               int recv_port = DEFAULT_COMMAND_PORT)
        : nx_ip_(nx_ip)
        , send_port_(send_port)
        , recv_port_(recv_port)
    {
        sock_send_ = -1;
        sock_recv_ = -1;
        std::memset(&guarded_cmd_, 0, sizeof(guarded_cmd_));
        std::memset(&pending_send_, 0, sizeof(pending_send_));
        guarded_cmd_.last_recv_time = 0.0;
    }

    ~CommBridge() {
        Stop();
    }

    // ========================================================================
    // Lifecycle
    // ========================================================================

    /// Launch send and receive threads.  Call once after construction.
    void Start() {
        if (running_.load()) return;  // already started

        // --- create send socket ---
        sock_send_ = socket(AF_INET, SOCK_DGRAM, 0);
        if (sock_send_ < 0) {
            std::cerr << "[CommBridge] Failed to create send socket" << std::endl;
            return;
        }
        std::memset(&nx_send_addr_, 0, sizeof(nx_send_addr_));
        nx_send_addr_.sin_family = AF_INET;
        nx_send_addr_.sin_port   = htons(send_port_);
        nx_send_addr_.sin_addr.s_addr = inet_addr(nx_ip_.c_str());

        // --- create recv socket ---
        sock_recv_ = socket(AF_INET, SOCK_DGRAM, 0);
        if (sock_recv_ < 0) {
            std::cerr << "[CommBridge] Failed to create recv socket" << std::endl;
            close(sock_send_);
            sock_send_ = -1;
            return;
        }
        // Allow re-binding to the same port after restart
        int reuse = 1;
        setsockopt(sock_recv_, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse));

        // Set recv timeout so the thread can check running_ periodically
        struct timeval tv;
        tv.tv_sec  = 0;
        tv.tv_usec = 100000;  // 100 ms
        setsockopt(sock_recv_, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

        struct sockaddr_in recv_addr;
        std::memset(&recv_addr, 0, sizeof(recv_addr));
        recv_addr.sin_family      = AF_INET;
        recv_addr.sin_port        = htons(recv_port_);
        recv_addr.sin_addr.s_addr = INADDR_ANY;
        if (bind(sock_recv_, (struct sockaddr*)&recv_addr, sizeof(recv_addr)) < 0) {
            std::cerr << "[CommBridge] Failed to bind recv socket to port "
                      << recv_port_ << std::endl;
            close(sock_send_);  sock_send_ = -1;
            close(sock_recv_);  sock_recv_ = -1;
            return;
        }

        running_.store(true);
        seq_ = 0;

        send_thread_ = std::thread(&CommBridge::SendThread, this);
        recv_thread_ = std::thread(&CommBridge::RecvThread, this);

        std::cout << "[CommBridge] Started — sending to " << nx_ip_
                  << ":" << send_port_ << ", listening on :" << recv_port_ << std::endl;
    }

    /// Stop threads and close sockets.  Safe to call multiple times.
    void Stop() {
        running_.store(false);
        if (send_thread_.joinable()) send_thread_.join();
        if (recv_thread_.joinable()) recv_thread_.join();
        if (sock_send_ >= 0) { close(sock_send_); sock_send_ = -1; }
        if (sock_recv_ >= 0) { close(sock_recv_); sock_recv_ = -1; }
        // Reset handshake flag so re-entry starts fresh
        std::lock_guard<std::mutex> lock(cmd_mutex_);
        guarded_cmd_.has_ready = false;
        guarded_cmd_.last_recv_time = 0.0;
    }

    // ========================================================================
    // Main-loop API  (called from RLControlStateRemote at 2 kHz)
    // ========================================================================

    /**
     * @brief Thread-safe copy of the latest command received from NX.
     * @param joint_command_out  [out] 12×5 matrix [kp | q_des | kd | v_des | tau_ff]
     * @return true if a valid command was available, false if no command ever received
     *
     * This is called every iteration of the 2 kHz main loop. The mutex is held
     * only for the duration of the memcpy — O(1) with a small constant.
     */
    bool GetLatestCommand(MatXf& joint_command_out) {
        std::lock_guard<std::mutex> lock(cmd_mutex_);
        if (guarded_cmd_.last_recv_time == 0.0) {
            return false;  // never received a packet
        }
        // Assemble 12×5 matrix from the stored CommandPacket
        for (int i = 0; i < 12; ++i) {
            joint_command_out(i, 0) = guarded_cmd_.pkt.kp[i];               // col 0: kp
            joint_command_out(i, 1) = guarded_cmd_.pkt.joint_pos_des[i];    // col 1: q_des
            joint_command_out(i, 2) = guarded_cmd_.pkt.kd[i];               // col 2: kd
            joint_command_out(i, 3) = guarded_cmd_.pkt.joint_vel_des[i];   // col 3: v_des
            joint_command_out(i, 4) = guarded_cmd_.pkt.tau_ff[i];          // col 4: tau_ff
        }
        return true;
    }

    /**
     * @brief Check whether communication has timed out.
     * @return true if no packet received for longer than timeout_ms_
     */
    bool IsTimeout() const {
        std::lock_guard<std::mutex> lock(cmd_mutex_);
        if (guarded_cmd_.last_recv_time == 0.0) {
            return false;  // never started receiving — not a timeout yet
        }
        double now = NowMs();
        return (now - guarded_cmd_.last_recv_time) > timeout_ms_;
    }

    /// Number of consecutive missed packets (resets on successful recv)
    int GetMissedPackets() const {
        std::lock_guard<std::mutex> lock(cmd_mutex_);
        return guarded_cmd_.missed_count;
    }

    /// Force-reset the timeout state (e.g. when re-entering RL control after a timeout)
    void ResetTimeout() {
        std::lock_guard<std::mutex> lock(cmd_mutex_);
        guarded_cmd_.last_recv_time = NowMs();
        guarded_cmd_.missed_count   = 0;
    }

    /// Check whether NX has sent the READY handshake heartbeat
    bool HasReceivedReady() const {
        std::lock_guard<std::mutex> lock(cmd_mutex_);
        return guarded_cmd_.has_ready;
    }

    /// Reset handshake state (call before re-entering handshake)
    void ResetReady() {
        std::lock_guard<std::mutex> lock(cmd_mutex_);
        guarded_cmd_.has_ready = false;
    }

    /**
     * @brief Update the sensor + user-command data that will be sent to NX.
     *
     * Called from the 2 kHz main loop. The actual send happens at a lower
     * rate (~50 Hz) in SendThread. We store the latest data under a mutex
     * so the send thread always has the freshest values.
     */
    void UpdateSensorData(const RobotBasicState& rbs,
                          const UserCommand& uc,
                          int current_state,
                          uint32_t timestamp_ms) {
        std::lock_guard<std::mutex> lock(send_mutex_);
        pending_send_.timestamp_ms  = timestamp_ms;
        pending_send_.current_state = current_state;
        for (int i = 0; i < 3; ++i) {
            pending_send_.rpy[i]    = rbs.base_rpy(i);
            pending_send_.acc[i]    = rbs.base_acc(i);
            pending_send_.omega[i]  = rbs.base_omega(i);
        }
        for (int i = 0; i < 12; ++i) {
            pending_send_.joint_pos[i] = rbs.joint_pos(i);
            pending_send_.joint_vel[i] = rbs.joint_vel(i);
            pending_send_.joint_tau[i] = rbs.joint_tau(i);
        }
        pending_send_.cmd_vel[0] = uc.forward_vel_scale;
        pending_send_.cmd_vel[1] = uc.side_vel_scale;
        pending_send_.cmd_vel[2] = uc.turnning_vel_scale;
    }

    /// Configure the send rate (default 40 → 2000/40 = 50 Hz)
    void SetSendDecimation(int d) { send_decimation_ = d; }

    /// Configure the communication timeout in milliseconds (default 40)
    void SetTimeoutMs(double ms) { timeout_ms_ = ms; }

private:
    // ========================================================================
    // Send thread  (~50 Hz, timerfd + epoll)
    // ========================================================================

    void SendThread() {
        // Create timerfd for 50 Hz (20 ms period)
        int tfd = timerfd_create(CLOCK_MONOTONIC, 0);
        if (tfd < 0) { std::cerr << "[CommBridge] timerfd_create failed" << std::endl; return; }

        struct itimerspec time_intv;
        long period_ns = (1000L * 1000L * 1000L) * send_decimation_ / 2000;  // ns per send tick
        time_intv.it_value.tv_sec  = 0;
        time_intv.it_value.tv_nsec = period_ns;
        time_intv.it_interval.tv_sec  = 0;
        time_intv.it_interval.tv_nsec = period_ns;
        timerfd_settime(tfd, 0, &time_intv, nullptr);

        int efd = epoll_create1(0);
        if (efd < 0) { close(tfd); return; }

        struct epoll_event ev;
        ev.data.fd = tfd;
        ev.events  = EPOLLIN;
        epoll_ctl(efd, EPOLL_CTL_ADD, tfd, &ev);

        struct epoll_event events[1];
        std::cout << "[CommBridge] Send thread running at "
                  << (2000.0 / send_decimation_) << " Hz" << std::endl;

        while (running_.load()) {
            int n = epoll_wait(efd, events, 1, -1);
            if (n < 0) continue;

            uint64_t val;
            read(tfd, &val, sizeof(val));  // consume timer event

            // Copy the latest sensor data under the send mutex
            SensorPacket pkt;
            {
                std::lock_guard<std::mutex> lock(send_mutex_);
                pkt = pending_send_;
            }
            pkt.seq = htonl(seq_++);

            sendto(sock_send_, &pkt, sizeof(pkt), 0,
                   (struct sockaddr*)&nx_send_addr_, sizeof(nx_send_addr_));
        }

        close(efd);
        close(tfd);
    }

    // ========================================================================
    // Receive thread  (blocking recvfrom with 100 ms timeout)
    // ========================================================================

    void RecvThread() {
        CommandPacket pkt;
        struct sockaddr_in from_addr;
        socklen_t from_len = sizeof(from_addr);

        std::cout << "[CommBridge] Recv thread started, listening on port "
                  << recv_port_ << std::endl;

        while (running_.load()) {
            std::memset(&pkt, 0, sizeof(pkt));
            ssize_t n = recvfrom(sock_recv_, &pkt, sizeof(pkt), 0,
                                 (struct sockaddr*)&from_addr, &from_len);

            if (n < 0) {
                // Timeout or error — just loop and check running_ again
                continue;
            }

            if (static_cast<size_t>(n) != sizeof(CommandPacket)) {
                std::cerr << "[CommBridge] Received " << n
                          << " bytes, expected " << sizeof(CommandPacket)
                          << " — ignoring malformed packet" << std::endl;
                continue;
            }

            // Check for shutdown sentinel
            uint32_t rx_seq = ntohl(pkt.seq);
            if (rx_seq == SHUTDOWN_SEQUENCE) {
                std::cout << "[CommBridge] Received shutdown from NX" << std::endl;
                std::lock_guard<std::mutex> lock(cmd_mutex_);
                guarded_cmd_.last_recv_time = 0.0;
                guarded_cmd_.missed_count   = 999;
                continue;
            }

            // Store the received command
            {
                std::lock_guard<std::mutex> lock(cmd_mutex_);
                guarded_cmd_.pkt            = pkt;
                guarded_cmd_.last_recv_time  = NowMs();
                guarded_cmd_.missed_count    = 0;
                // Handshake: check for READY heartbeat
                if (ntohl(pkt.heartbeat) == HEARTBEAT_READY) {
                    guarded_cmd_.has_ready = true;
                }
            }
        }

        std::cout << "[CommBridge] Recv thread stopped" << std::endl;
    }

    // ========================================================================
    // Helpers
    // ========================================================================

    /// Monotonic time in milliseconds
    static double NowMs() {
        struct timespec ts;
        clock_gettime(CLOCK_MONOTONIC, &ts);
        return ts.tv_sec * 1e3 + ts.tv_nsec * 1e-6;
    }

    // ========================================================================
    // Per-instance state
    // ========================================================================

    std::string nx_ip_;
    int send_port_, recv_port_;

    int sock_send_, sock_recv_;
    struct sockaddr_in nx_send_addr_;

    // Guarded command from NX (recv thread writes, main loop reads)
    struct GuardedCommand {
        CommandPacket pkt;
        double        last_recv_time;   // monotonic ms
        int           missed_count;
        bool          has_ready = false; // handshake: NX sent HEARTBEAT_READY
    };
    GuardedCommand guarded_cmd_;
    mutable std::mutex cmd_mutex_;

    // Pending sensor data (main loop writes, send thread reads)
    SensorPacket pending_send_;
    std::mutex send_mutex_;

    // Threads
    std::thread send_thread_, recv_thread_;
    std::atomic<bool> running_{false};

    // Configuration
    int    send_decimation_ = 40;   // 2000/40 = 50 Hz
    double timeout_ms_      = 40.0; // 2 missed packets at 50 Hz
    uint32_t seq_           = 0;
};
